### ISSUE TITLE
Error in Building Code using scons command

### ISSUE THREAD

**Issue by barryallen94** [jgharehchamani/SSE#1]
While executing scons command (In Building through SConstruct), I am getting the following error:

scons: Reading SConscript files ...
/home/~
/home/~/bin:/home/~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
scons: done reading SConscript files.
scons: Building targets ...
g++ -o test_horus.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp -Ibuild test_horus.cpp
g++ -o build/horus/AES.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/horus/AES.cpp
g++ -o build/horus/AVLTree.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/horus/AVLTree.cpp
g++ -o build/horus/Bid.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/horus/Bid.cpp
build/horus/Bid.cpp: In member function ‘Bid Bid::operator++()’:
build/horus/Bid.cpp:36:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
build/horus/Bid.cpp: In member function ‘Bid& Bid::operator=(int)’:
build/horus/Bid.cpp:43:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
build/horus/Bid.cpp: In member function ‘Bid& Bid::operator=(std::vector<unsigned char>)’:
build/horus/Bid.cpp:129:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
g++ -o build/horus/Horus.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/horus/Horus.cpp
g++ -o build/horus/OMAP.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/horus/OMAP.cpp
g++ -o build/horus/ORAM.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/horus/ORAM.cpp
g++ -o build/horus/PRFORAM.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/horus/PRFORAM.cpp
g++ -o build/horus/RAMStore.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/horus/RAMStore.cpp
g++ -o build/aux/db_generator.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/aux/db_generator.cpp
g++ -o build/utils/Utilities.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/utils/Utilities.cpp
g++ -o build/utils/logger.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/utils/logger.cpp
g++ -o build/utils/rocksdb_wrapper.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/utils/rocksdb_wrapper.cpp
g++ -o build/utils/utils.o -c -std=c++14 -fPIC -Wall -march=native -g -O0 -DBENCHMARK -Ibuild -I/usr/local/include -Ithird_party/crypto/library/include -Ithird_party/db-parser/library/include -I/usr/local/include/cryptopp build/utils/utils.cpp
g++ -o horus_debug -Wl,-rpath=/home/~/SSE_New/SSE/third_party/crypto/library/lib -Wl,-rpath=/home/~/SSE_New/SSE/third_party/db-parser/library/lib test_horus.o build/horus/AES.o build/horus/AVLTree.o build/horus/Bid.o build/horus/Horus.o build/horus/OMAP.o build/horus/ORAM.o build/horus/PRFORAM.o build/horus/RAMStore.o build/aux/db_generator.o build/utils/Utilities.o build/utils/logger.o build/utils/rocksdb_wrapper.o build/utils/utils.o -L/usr/local/lib -Lthird_party/crypto/library/lib -Lthird_party/db-parser/library/lib -lcrypto -lsse_crypto -lgrpc++_unsecure -lgrpc -lprotobuf -lpthread -ldl -lsse_dbparser -lrocksdb -lsnappy -lz -lbz2 -llz4 -lcryptopp
/usr/local/lib/librocksdb.a(options_helper.o): In function `rocksdb::ZSTD_Supported()':
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:84: undefined reference to `ZSTD_versionNumber'
/usr/local/lib/librocksdb.a(format.o): In function `rocksdb::ZSTD_Uncompress(char const*, unsigned long, int*, rocksdb::Slice const&)':
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:775: undefined reference to `ZSTD_createDCtx'
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:778: undefined reference to `ZSTD_decompress_usingDict'
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:779: undefined reference to `ZSTD_freeDCtx'
/usr/local/lib/librocksdb.a(column_family.o): In function `rocksdb::ZSTD_Supported()':
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:84: undefined reference to `ZSTD_versionNumber'
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:84: undefined reference to `ZSTD_versionNumber'
/usr/local/lib/librocksdb.a(db_impl.o): In function `rocksdb::ZSTD_Supported()':
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:84: undefined reference to `ZSTD_versionNumber'
/usr/local/lib/librocksdb.a(block_based_table_builder.o): In function `rocksdb::ZSTD_Compress(rocksdb::CompressionOptions const&, char const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, rocksdb::Slice const&)':
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:738: undefined reference to `ZSTD_compressBound'
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:742: undefined reference to `ZSTD_createCCtx'
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:745: undefined reference to `ZSTD_compress_usingDict'
/home/~/SSE_New/rocksdb-rocksdb-5.7.5/./util/compression.h:746: undefined reference to `ZSTD_freeCCtx'
collect2: error: ld returned 1 exit status
scons: *** [horus_debug] Error 1
scons: building terminated because of errors.

**Comment by jgharehchamani** [comment]
What is your OS? Have you installed the pre-requisites as mentioned in README?

**Comment by barryallen94** [comment]
OS: Ubuntu 16.04
Yes, I have installed the pre-requisites as mentioned in README.

**Comment by jgharehchamani** [comment]
I think your previously installed packages have some conflict with new ones (specifically RocksDB). I suggest you use a brand new Ubuntu (maybe in VM). For Ubuntu 16.04, it is not required to do the following lines of README:
```
$ sudo apt-get install gcc-5 g++-5
$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
$ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
```
Actually, I have repeated these steps more than 10 times on fresh Ubuntu (14.04 and 16.06). 
Let me know if you still have the problem after trying on a fresh OS.
