### ISSUE TITLE
Error in Building Code (some Macros were not declared in this scope).

### ISSUE THREAD

**Issue by YinFFF** [jgharehchamani/SSE#2]
While executing command "scons deps", I am getting the following error:

scons: Reading SConscript files ...
/root
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
scons: done reading SConscript files.
scons: Building targets ...
cd third_party/crypto && scons lib static_relic=0
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++      src/puncturable_enc.cpp  => build/puncturable_enc.o
In file included from src/ppke/GMPpke.h:13:0,
                 from src/puncturable_enc.cpp:12:
src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator==(const relicxx::ZR&, const relicxx::ZR&)’:
src/ppke/relic_wrapper/relic_api.h:165:31: error: ‘CMP_EQ’ was not declared in this scope
       {if(bn_cmp(x.z, y.z) == CMP_EQ) return true; else return false; }
                               ^
src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator!=(const relicxx::ZR&, const relicxx::ZR&)’:
src/ppke/relic_wrapper/relic_api.h:167:32: error: ‘CMP_EQ’ was not declared in this scope
       {if (bn_cmp(x.z, y.z) != CMP_EQ) return true; else return false; }
                                ^
src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator>(const relicxx::ZR&, const relicxx::ZR&)’:
src/ppke/relic_wrapper/relic_api.h:169:32: error: ‘CMP_GT’ was not declared in this scope
       {if (bn_cmp(x.z, y.z) == CMP_GT) return true; else return false; }
                                ^
src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator<(const relicxx::ZR&, const relicxx::ZR&)’:
src/ppke/relic_wrapper/relic_api.h:171:32: error: ‘CMP_LT’ was not declared in this scope
       {if (bn_cmp(x.z, y.z) == CMP_LT) return true; else return false; }
                                ^
src/ppke/relic_wrapper/relic_api.h: At global scope:
src/ppke/relic_wrapper/relic_api.h:181:49: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kByteSize = 1 + 2*FP_BYTES;
                                                 ^
src/ppke/relic_wrapper/relic_api.h:182:54: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kCompactByteSize = 1 + FP_BYTES;
                                                      ^
src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator==(const relicxx::G1&, const relicxx::G1&)’:
src/ppke/relic_wrapper/relic_api.h:238:35: error: ‘CMP_EQ’ was not declared in this scope
       {return g1_cmp(x.g, y.g) == CMP_EQ; }
                                   ^
src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator!=(const relicxx::G1&, const relicxx::G1&)’:
src/ppke/relic_wrapper/relic_api.h:240:35: error: ‘CMP_EQ’ was not declared in this scope
       {return g1_cmp(x.g, y.g) != CMP_EQ; }
                                   ^
src/ppke/relic_wrapper/relic_api.h: At global scope:
src/ppke/relic_wrapper/relic_api.h:246:49: error: ‘FP_BYTES’ was not declared in this scope
      constexpr static uint16_t kByteSize = 1 + 4*FP_BYTES;
src/ppke/relic_wrapper/relic_api.h:247:56: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kCompactByteSize = 1 + 2*FP_BYTES;
                                                        ^
src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator==(const relicxx::G2&, const relicxx::G2&)’:
src/ppke/relic_wrapper/relic_api.h:300:71: error: ‘CMP_EQ’ was not declared in this scope
       {return g2_cmp( const_cast<G2&>(x).g,  const_cast<G2&>(y).g) == CMP_EQ;}
                                                                       ^
src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator!=(const relicxx::G2&, const relicxx::G2&)’:
src/ppke/relic_wrapper/relic_api.h:302:71: error: ‘CMP_EQ’ was not declared in this scope
       {return g2_cmp( const_cast<G2&>(x).g,  const_cast<G2&>(y).g) != CMP_EQ;}
                                                                       ^
src/ppke/relic_wrapper/relic_api.h: At global scope:
src/ppke/relic_wrapper/relic_api.h:308:48: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kByteSize = 12 * FP_BYTES;
                                                ^
src/ppke/relic_wrapper/relic_api.h:309:54: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kCompactByteSize = 8 * FP_BYTES;
                                                      ^
src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator==(const relicxx::GT&, const relicxx::GT&)’:
src/ppke/relic_wrapper/relic_api.h:362:70: error: ‘CMP_EQ’ was not declared in this scope
       { return gt_cmp(const_cast<GT&>(x).g, const_cast<GT&>(y).g) == CMP_EQ;}
                                                                      ^
src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator!=(const relicxx::GT&, const relicxx::GT&)’:
src/ppke/relic_wrapper/relic_api.h:364:71: error: ‘CMP_EQ’ was not declared in this scope
       { return  gt_cmp(const_cast<GT&>(x).g, const_cast<GT&>(y).g) != CMP_EQ;}
                                                                       ^
src/ppke/relic_wrapper/relic_api.h: At global scope:
src/ppke/relic_wrapper/relic_api.h:393:52: error: ‘RELIC_BN_BYTES’ was not declared in this scope
     constexpr static unsigned int kPrfOutputSize = RELIC_BN_BYTES + kStatisticalSecurity/8;
                                                    ^
src/ppke/relic_wrapper/relic_api.h:396:60: error: could not convert template argument ‘relicxx::PairingGroup::kPrfOutputSize’ to ‘short unsigned int’
     ZR pseudoRandomZR(const sse::crypto::Prf<kPrfOutputSize> &prf, const std::string &seed) const;
                                                            ^
In file included from src/puncturable_enc.cpp:12:0:
src/ppke/GMPpke.h:261:58: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ to ‘short unsigned int’
     void keygen(const sse::crypto::Prf<kPPKEPrfOutputSize> &prf, GmppkePublicKey & pk, GmppkePrivateKey & sk, GmppkeSecretParameters &sp) const;
src/ppke/GMPpke.h:263:60: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ to ‘short unsigned int’
     void paramgen(const sse::crypto::Prf<kPPKEPrfOutputSize> &prf, GmppkeSecretParameters &sp) const;
                                                            ^
src/ppke/GMPpke.h:343:75: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ to ‘short unsigned int’
     GmppkePrivateKeyShare sk0Gen(const sse::crypto::Prf<kPPKEPrfOutputSize> &prf, const GmppkeSecretParameters &sp, size_t d) const;
                                                                           ^
src/ppke/GMPpke.h:344:79: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ to ‘short unsigned int’
     GmppkePrivateKeyShare skShareGen(const sse::crypto::Prf<kPPKEPrfOutputSize> &prf, const GmppkeSecretParameters &sp, size_t d, const tag_type& tag) const;
                                                                               ^
src/ppke/GMPpke.h:357:65: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ to ‘short unsigned int’
     void keygenPartial(const sse::crypto::Prf<kPPKEPrfOutputSize> &prf, const relicxx::ZR & alpha, GmppkePublicKey & pk, GmppkePrivateKey & sk, const GmppkeSecretParameters &sp
                                                                 ^
src/ppke/GMPpke.h:360:74: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ to ‘short unsigned int’
     GmppkePrivateKeyShare skgen(const sse::crypto::Prf<kPPKEPrfOutputSize> &prf, const GmppkeSecretParameters &sp ) const;
                                                                          ^
src/ppke/GMPpke.h: In member function ‘sse::crypto::GmmppkeCT<T> sse::crypto::Gmppke::encrypt(const sse::crypto::GmppkePublicKey&, const T&, const tag_type&) const’:
src/ppke/GMPpke.h:280:32: error: ‘FP_BYTES’ was not declared in this scope
         std::array<uint8_t, 12*FP_BYTES> gt_blind_bytes;
                                ^
src/ppke/GMPpke.h:280:40: error: template argument 2 is invalid
         std::array<uint8_t, 12*FP_BYTES> gt_blind_bytes;
                                        ^
src/ppke/GMPpke.h:281:85: error: request for member ‘size’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
         group.exp(group.pair(pk.g2G1, pk.ppkeg1), s).getBytes(false, gt_blind_bytes.size(), gt_blind_bytes.data());
                                                                                     ^
src/ppke/GMPpke.h:281:108: error: request for member ‘data’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
         group.exp(group.pair(pk.g2G1, pk.ppkeg1), s).getBytes(false, gt_blind_bytes.size(), gt_blind_bytes.data());
                                                                                                            ^
src/ppke/GMPpke.h:284:34: error: request for member ‘data’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
         hkdf.hmac(gt_blind_bytes.data(), gt_blind_bytes.size(), (uint8_t*) &mask, sizeof(mask));
                                  ^
src/ppke/GMPpke.h:284:57: error: request for member ‘size’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
         hkdf.hmac(gt_blind_bytes.data(), gt_blind_bytes.size(), (uint8_t*) &mask, sizeof(mask));
                                                         ^
src/ppke/GMPpke.h: In member function ‘sse::crypto::GmmppkeCT<T> sse::crypto::Gmppke::encrypt(const sse::crypto::GmppkeSecretParameters&, const T&, const tag_type&) const’:
src/ppke/GMPpke.h:299:32: error: ‘FP_BYTES’ was not declared in this scope
         std::array<uint8_t, 12*FP_BYTES> gt_blind_bytes;
                                ^
src/ppke/GMPpke.h:299:40: error: template argument 2 is invalid
         std::array<uint8_t, 12*FP_BYTES> gt_blind_bytes;
                                        ^
src/ppke/GMPpke.h:300:91: error: request for member ‘size’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
         group.exp(group.generatorGT(), sp.alpha*sp.beta*s).getBytes(false, gt_blind_bytes.size(), gt_blind_bytes.data());

src/ppke/GMPpke.h:300:114: error: request for member ‘data’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
         group.exp(group.generatorGT(), sp.alpha*sp.beta*s).getBytes(false, gt_blind_bytes.size(), gt_blind_bytes.data());
                                                                                                                  ^
src/ppke/GMPpke.h:303:34: error: request for member ‘data’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
         hkdf.hmac(gt_blind_bytes.data(), gt_blind_bytes.size(), (uint8_t*) &mask, sizeof(mask));
                                  ^
src/ppke/GMPpke.h:303:57: error: request for member ‘size’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
         hkdf.hmac(gt_blind_bytes.data(), gt_blind_bytes.size(), (uint8_t*) &mask, sizeof(mask));
                                                         ^
src/puncturable_enc.cpp: At global scope:
src/puncturable_enc.cpp:63:54: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ to ‘short unsigned int’
             const sse::crypto::Prf<kPPKEPrfOutputSize> master_prf_;
                                                      ^
src/puncturable_enc.cpp: In constructor ‘sse::crypto::PuncturableEncryption::PEncImpl::PEncImpl(const master_key_type&)’:
src/puncturable_enc.cpp:67:133: error: expression list treated as compound expression in mem-initializer [-fpermissive]
         PuncturableEncryption::PEncImpl::PEncImpl(const punct::master_key_type& key) : master_prf_(key.data(), punct::kMasterKeySize)
                                                                                                                                     ^
scons: *** [build/puncturable_enc.o] Error 1
scons: building terminated because of errors.
scons: *** [third_party/crypto/library] Error 2
scons: building terminated because of errors.

**Comment by YinFFF** [comment]
My OS version is "Ubuntu 14.04.3 LTS", thanks!

**Comment by jgharehchamani** [comment]
Hi,
This problem occurs because of some updates in Relic repository.
I added a new command in the building procedure of Relic which fixes your issue.

**Comment by YinFFF** [comment]
It works! 
Thanks.
