### ISSUE TITLE
Always Error!!!

### ISSUE THREAD

**Issue by XWHQSJ** [jgharehchamani/SSE#3]
Has anyone run the code successfully?

Now, I have two errors:
1. /usr/bin/ld: build/horus/AES.o: undefined reference to symbol 'OPENSSL_add_all_algorithms_noconf@@OPENSSL_1.0.0'
2. //lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line

when build the src:
g++ -o horus_debug -Wl,-rpath=/home/wanhui/SSE/third_party/crypto/library/lib -Wl,-rpath=/home/wanhui/SSE/third_party/db-parser/library/lib test_horus.o build/horus/AES.o build/horus/AVLTree.o build/horus/Bid.o build/horus/Horus.o build/horus/OMAP.o build/horus/ORAM.o build/horus/PRFORAM.o build/horus/RAMStore.o build/aux/db_generator.o build/utils/Utilities.o build/utils/logger.o build/utils/rocksdb_wrapper.o build/utils/utils.o -L/usr/local/lib -Lthird_party/crypto/library/lib -Lthird_party/db-parser/library/lib -lcrypto -lsse_crypto -lgrpc++_unsecure -lgrpc -lprotobuf -lpthread -ldl -lsse_dbparser -lrocksdb -lsnappy -lz -lbz2 -llz4 -lcryptopp

I Need Help, Please!

**Comment by XWHQSJ** [comment]
My OS is "Ubuntu 16.04 LTS"

**Comment by chengzhix** [comment]
Hi，did you finally install successfully?  I had the same error.
